apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        api: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: officialphemi/udagram-api-feed
        ports:
        - containerPort: 80
      restartPolicy: Always
