apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-api-user
  template:
    metadata:
      labels:
        api: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: officialphemi/udagram-api-user
        ports:
        - containerPort: 80
      restartPolicy: Always
